app:
  name: "springbootmystarter"
  description: "${app.name} is a Spring Boot application"

dubbo:
  application:
    name: "my-provider"
  protocol:
    name: "dubbo"
    port: 20880
  registry:
    address: "N/A"