app:
  name: "springboottest"
  description: "${app.name} is a Spring Boot application"

server:
  port: 9090



my:
  testprop: "testprop"

dubbo:
  application:
    name: "my-cosumer"
  registry:
    address: "zookeeper://127.0.0.1:2181"
