app:
  name: "spring-cloud-provider-test"
  description: "${app.name} is a Spring Boot application"

dubbo:
  application:
    name: "my-cloud-provider"
  protocol:
    name: "dubbo"
    port: 20880
  registry:
    address: "zookeeper://127.0.0.1:2181"